-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "black_time" INTEGER NOT NULL DEFAULT 300000,
ADD COLUMN     "last_move_at" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "white_time" INTEGER NOT NULL DEFAULT 300000;
